### ISSUE TITLE
Fix the unclean zero conditions in imu.c

### ISSUE THREAD

**Issue by Crashpilot1000** [multiwii/multiwii-firmware#8]
A div by zero will occur in the _atan2 (https://github.com/multiwii/multiwii-firmware/blob/upstream_shared/IMU.cpp#L134)
Code with no div by zero would be this:
int16_t _atan2(int32_t y, int32_t x)
{
    float z = y;
    int16_t a;
    uint8_t c;
    c = abs(y) < abs(x);
    if (c)
    {
        if(x) z = z / x;
        else return 0;
    }
    else
    {
        if(y) z = x / z;
        else return 0;
    }
    a = 2046.43 \* (z / (3.5714 + z \* z));
    if (c)
    {
        if (x < 0)
        {
            if (y < 0) a -= 1800;
            else       a += 1800;
        }
    }
    else
    {
        a = 900 - a;
        if (y < 0) a -= 1800;
    }
    return a;
}

The next thing is the possibility of feeding InvSqrt with zero here: https://github.com/multiwii/multiwii-firmware/blob/upstream_shared/IMU.cpp#L270 resulting in a bogus value (no div zero this time..).
That could be avoided:
...
int32_t zerochk = sqGX_sqGZ + mul(EstG.V16.Y,EstG.V16.Y);
if(!zerochk) return;
invG = InvSqrt(zerochk);
...
Plz _somehow_ fix that.

Ps: That InvSqrt has more precision (2.6 times):
    float InvSqrt(float x)
    {
       uint32_t i = 0x5F1FFFF9 - (\* (uint32_t_)&x >> 1);
       float  tmp = \* (float_)&i;
       return tmp \* (1.68191409f - 0.703952253f \* x \* tmp \* tmp);
    }               

see http://www.multiwii.com/forum/viewtopic.php?f=8&t=4246&start=50#p50981

**Comment by fiendie** [comment]
Sorry, but this is just a 1:1 mirror of the Google Code project.

**Comment by Crashpilot1000** [comment]
Where can I file issues then?

**Comment by fiendie** [comment]
I fear you have to go through the forum. As far as I know there is no proper issue tracker :/
